//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_PhysicsVR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.physicsVR_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Index
        {
            get
            {
                return SteamVR_Actions.physicsVR_Index;
            }
        }
        
        public virtual SteamVR_Action_Boolean Thumb
        {
            get
            {
                return SteamVR_Actions.physicsVR_Thumb;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptics
        {
            get
            {
                return SteamVR_Actions.physicsVR_Haptics;
            }
        }
    }
}
